[package]
name = "tls-psk-tunnel"
version = "0.1.0"
authors = ["Asim Ihsan <asim.ihsan@gmail.com>"]
edition = "2018"

[lib]
name = "tlspsklib"
path = "src/lib.rs"

[dependencies]
futures = "0.3.5"
openssl = "0.10.30"
tokio = { version = "0.2.22", features = ["full"] }
tokio-openssl = "0.4.0"